# Generated by Django 5.2.1 on 2025-07-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('truck_number', models.CharField(max_length=50)),
                ('dims', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('broker_name', models.CharField(max_length=100)),
                ('bol', models.FileField(blank=True, null=True, upload_to='bol/')),
                ('rc', models.FileField(blank=True, null=True, upload_to='rc/')),
                ('miles', models.DecimalField(decimal_places=2, max_digits=7)),
                ('disp_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Dispatcher %')),
                ('pod', models.FileField(blank=True, null=True, upload_to='pod/')),
                ('booked_on', models.DateField()),
                ('drivers_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='list.disp')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='list.driver')),
            ],
        ),
    ]
