# Generated by Django 5.2.1 on 2025-08-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_per_mile',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount per mile (0.50 means $0.5 per mile)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percent of gross (30.00 means 30%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='pay_type',
            field=models.CharField(choices=[('percent_of_gross', 'Percent of gross'), ('per_mile', 'Per mile')], default='percent_of_gross', max_length=20),
        ),
    ]
