# Generated by Django 5.2.1 on 2025-08-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_driver_driver_per_mile_driver_driver_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
