# Generated by Django 5.2.1 on 2025-08-24 23:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='broker_name',
        ),
        migrations.AddField(
            model_name='load',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='list.broker'),
        ),
        migrations.AlterField(
            model_name='load',
            name='disp_percent',
            field=models.DecimalField(choices=[(Decimal('1.00'), '1%'), (Decimal('2.00'), '2%'), (Decimal('3.00'), '3%'), (Decimal('5.00'), '5%')], decimal_places=2, default=Decimal('3.00'), max_digits=5, verbose_name='Dispatcher %'),
        ),
    ]
