# Generated by Django 5.2.1 on 2025-08-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_remove_load_broker_name_load_broker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='drivers_rate',
        ),
        migrations.AddField(
            model_name='load',
            name='company_profit_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='dispatcher_payout_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='drivers_payout_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
